spring:
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    enabled: true
    suffix: .html
    check-template: true
    check-template-location: true
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  redis:
    port: 6379
    host: 127.0.0.1

server:
  tomcat:
    max-http-post-size: -1


comment.avatar: /images/dog.jpg